# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\LMXControlPanel.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FieldSignalGenerator(object):
    def setupUi(self, FieldSignalGenerator):
        FieldSignalGenerator.setObjectName("FieldSignalGenerator")
        FieldSignalGenerator.resize(834, 841)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Resource/icons/Defend Dynamics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FieldSignalGenerator.setWindowIcon(icon)
        FieldSignalGenerator.setStyleSheet("background-color: rgb(18, 32, 60);\n"
"color: rgb(230, 230, 230);")
        self.verticalLayout = QtWidgets.QVBoxLayout(FieldSignalGenerator)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(FieldSignalGenerator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {\n"
"    color: rgb(220, 235, 255);\n"
"    font: bold 25pt \"calibri\";\n"
"    padding: 10px;\n"
"    border: 2px solid rgb(60, 120, 200);\n"
"    border-radius: 8px;\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 rgb(45, 90, 160),\n"
"        stop:1 rgb(18, 32, 60)\n"
"    );\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("QGroupBox {\n"
"    border: 2px solid rgb(40, 70, 120);        /* navy-based border */\n"
"    background-color: rgba(25, 45, 80, 150);   /* slightly lighter navy */\n"
"    border-radius: 6px;\n"
"    margin-top: 12px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    margin-left: 8px;\n"
"    padding: 2px 6px;\n"
"    color: rgb(120, 170, 230);                 /* soft sky-blue title */\n"
"    background-color: transparent;\n"
"    font-weight: bold;\n"
"}")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_12 = QtWidgets.QFrame(self.groupBox_4)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.formLayout_4 = QtWidgets.QFormLayout(self.frame_12)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_14 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.CB_PL_Port = QtWidgets.QComboBox(self.frame_12)
        self.CB_PL_Port.setMinimumSize(QtCore.QSize(0, 30))
        self.CB_PL_Port.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.CB_PL_Port.setFont(font)
        self.CB_PL_Port.setStyleSheet("QComboBox {\n"
"    background-color: rgb(25, 45, 80);\n"
"    color: white;\n"
"    border: 2px solid rgb(40, 90, 150);\n"
"    border-radius: 5px;\n"
"    padding: 4px 25px 4px 8px;\n"
"}\n"
"\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border-left: 1px solid #2c3f5e;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/down_arrow_white.png); /* your white arrow icon */\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #111822;\n"
"    border: 1px solid #2c3f5e;\n"
"    selection-background-color: #4d79ff;\n"
"    color: white;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/ARrow.png);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}")
        self.CB_PL_Port.setObjectName("CB_PL_Port")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.CB_PL_Port)
        self.label_16 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.LE_PL_Baud = QtWidgets.QLineEdit(self.frame_12)
        self.LE_PL_Baud.setMinimumSize(QtCore.QSize(0, 30))
        self.LE_PL_Baud.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.LE_PL_Baud.setFont(font)
        self.LE_PL_Baud.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(20, 38, 70);\n"
"    color: rgb(230, 230, 230);\n"
"    border: 2px solid rgb(35, 75, 130);\n"
"    border-radius: 4px;\n"
"    padding: 4px 6px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(100, 170, 255);\n"
"    background-color: rgb(25, 50, 90);\n"
"}")
        self.LE_PL_Baud.setObjectName("LE_PL_Baud")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LE_PL_Baud)
        self.verticalLayout_10.addWidget(self.frame_12)
        self.PB_PL_Conn = QtWidgets.QPushButton(self.groupBox_4)
        self.PB_PL_Conn.setMinimumSize(QtCore.QSize(0, 40))
        self.PB_PL_Conn.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("calibri")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.PB_PL_Conn.setFont(font)
        self.PB_PL_Conn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(28, 55, 95);\n"
"    color: white;\n"
"    border: 2px solid rgb(40, 90, 150);\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"    font: 13pt \"calibri\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(50, 110, 190);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(20, 45, 80);\n"
"    border: 2px solid rgb(100, 170, 255);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/connected.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_PL_Conn.setIcon(icon1)
        self.PB_PL_Conn.setIconSize(QtCore.QSize(30, 30))
        self.PB_PL_Conn.setObjectName("PB_PL_Conn")
        self.verticalLayout_10.addWidget(self.PB_PL_Conn, 0, QtCore.Qt.AlignHCenter)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_11.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_4 = QtWidgets.QFrame(self.groupBox_5)
        self.frame_4.setStyleSheet("QPushButton {\n"
"    background-color: rgb(28, 55, 95);\n"
"    color: white;\n"
"    border: 2px solid rgb(40, 90, 150);\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"    font: 14pt \"calibri\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(50, 110, 190);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(20, 45, 80);\n"
"    border: 2px solid rgb(100, 170, 255);\n"
"}\n"
"\n"
"QSpinBox {\n"
"    background-color: rgb(22, 40, 75);\n"
"    color: rgb(230, 230, 230);\n"
"    border: 2px solid rgb(35, 75, 130);\n"
"    border-radius: 4px;\n"
"    padding: 4px 8px;\n"
"    font: 14pt \"calibri\";\n"
"}\n"
"\n"
"/* Hover */\n"
"QSpinBox:hover {\n"
"    border: 2px solid rgb(70, 140, 220);\n"
"}\n"
"\n"
"/* Focus (active input look) */\n"
"QSpinBox:focus {\n"
"    border: 2px solid rgb(100, 170, 255);\n"
"    background-color: rgb(25, 50, 90);\n"
"}\n"
"\n"
"\n"
"\n"
"/* Keep system arrows visible */\n"
"QSpinBox::up-arrow,\n"
"QSpinBox::down-arrow {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout.setObjectName("gridLayout")
        self.SB_PW = CustomDoubleSpinBox(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.SB_PW.setFont(font)
        self.SB_PW.setObjectName("SB_PW")
        self.gridLayout.addWidget(self.SB_PW, 2, 1, 1, 1)
        self.SB_Ledge_delay = CustomDoubleSpinBox(self.frame_4)
        self.SB_Ledge_delay.setObjectName("SB_Ledge_delay")
        self.gridLayout.addWidget(self.SB_Ledge_delay, 5, 1, 1, 1)
        self.SB_Tedge_delay = CustomDoubleSpinBox(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.SB_Tedge_delay.setFont(font)
        self.SB_Tedge_delay.setObjectName("SB_Tedge_delay")
        self.gridLayout.addWidget(self.SB_Tedge_delay, 6, 1, 1, 1)
        self.PB_Set_Ledge_delay = QtWidgets.QPushButton(self.frame_4)
        self.PB_Set_Ledge_delay.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.PB_Set_Ledge_delay.setFont(font)
        self.PB_Set_Ledge_delay.setObjectName("PB_Set_Ledge_delay")
        self.gridLayout.addWidget(self.PB_Set_Ledge_delay, 5, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.SB_Attenuation = QtWidgets.QSpinBox(self.frame_4)
        self.SB_Attenuation.setMinimumSize(QtCore.QSize(0, 30))
        self.SB_Attenuation.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.SB_Attenuation.setFont(font)
        self.SB_Attenuation.setObjectName("SB_Attenuation")
        self.gridLayout.addWidget(self.SB_Attenuation, 4, 1, 1, 1)
        self.label_tedge = QtWidgets.QLabel(self.frame_4)
        self.label_tedge.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_tedge.setFont(font)
        self.label_tedge.setObjectName("label_tedge")
        self.gridLayout.addWidget(self.label_tedge, 6, 0, 1, 1)
        self.label_ledge = QtWidgets.QLabel(self.frame_4)
        self.label_ledge.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_ledge.setFont(font)
        self.label_ledge.setObjectName("label_ledge")
        self.gridLayout.addWidget(self.label_ledge, 5, 0, 1, 1)
        self.SB_PRI = QtWidgets.QSpinBox(self.frame_4)
        self.SB_PRI.setMinimumSize(QtCore.QSize(0, 30))
        self.SB_PRI.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.SB_PRI.setFont(font)
        self.SB_PRI.setObjectName("SB_PRI")
        self.gridLayout.addWidget(self.SB_PRI, 3, 1, 1, 1)
        self.PB_Set_Tedge_delay = QtWidgets.QPushButton(self.frame_4)
        self.PB_Set_Tedge_delay.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.PB_Set_Tedge_delay.setFont(font)
        self.PB_Set_Tedge_delay.setObjectName("PB_Set_Tedge_delay")
        self.gridLayout.addWidget(self.PB_Set_Tedge_delay, 6, 2, 1, 1)
        self.SB_Frequency = QtWidgets.QSpinBox(self.frame_4)
        self.SB_Frequency.setMinimumSize(QtCore.QSize(0, 30))
        self.SB_Frequency.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.SB_Frequency.setFont(font)
        self.SB_Frequency.setStyleSheet("background-color: transparent;")
        self.SB_Frequency.setObjectName("SB_Frequency")
        self.gridLayout.addWidget(self.SB_Frequency, 0, 1, 1, 1)
        self.PB_Set_Attenuation = QtWidgets.QPushButton(self.frame_4)
        self.PB_Set_Attenuation.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.PB_Set_Attenuation.setFont(font)
        self.PB_Set_Attenuation.setObjectName("PB_Set_Attenuation")
        self.gridLayout.addWidget(self.PB_Set_Attenuation, 4, 2, 1, 1)
        self.PB_Set_pri = QtWidgets.QPushButton(self.frame_4)
        self.PB_Set_pri.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.PB_Set_pri.setFont(font)
        self.PB_Set_pri.setObjectName("PB_Set_pri")
        self.gridLayout.addWidget(self.PB_Set_pri, 3, 2, 1, 1)
        self.PB_Set_Frequency = QtWidgets.QPushButton(self.frame_4)
        self.PB_Set_Frequency.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.PB_Set_Frequency.setFont(font)
        self.PB_Set_Frequency.setStyleSheet("QPushButton {\n"
"    background-color: rgb(28, 55, 95);\n"
"    color: white;\n"
"    border: 2px solid rgb(40, 90, 150);\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"    font: 11pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(50, 110, 190);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(20, 45, 80);\n"
"    border: 2px solid rgb(100, 170, 255);\n"
"}")
        self.PB_Set_Frequency.setObjectName("PB_Set_Frequency")
        self.gridLayout.addWidget(self.PB_Set_Frequency, 0, 2, 1, 1)
        self.PB_Set_pw = QtWidgets.QPushButton(self.frame_4)
        self.PB_Set_pw.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.PB_Set_pw.setFont(font)
        self.PB_Set_pw.setObjectName("PB_Set_pw")
        self.gridLayout.addWidget(self.PB_Set_pw, 2, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        self.label_12.setMinimumSize(QtCore.QSize(0, 30))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.PB_Send_All = QtWidgets.QPushButton(self.frame_4)
        self.PB_Send_All.setMinimumSize(QtCore.QSize(0, 30))
        self.PB_Send_All.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("calibri")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.PB_Send_All.setFont(font)
        self.PB_Send_All.setStyleSheet("QPushButton {\n"
"    background-color: rgb(28, 55, 95);\n"
"    color: white;\n"
"    border: 2px solid rgb(40, 90, 150);\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"    font: 13pt \"calibri\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(50, 110, 190);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(20, 45, 80);\n"
"    border: 2px solid rgb(100, 170, 255);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/checkmark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_Send_All.setIcon(icon2)
        self.PB_Send_All.setObjectName("PB_Send_All")
        self.gridLayout.addWidget(self.PB_Send_All, 7, 1, 1, 1)
        self.verticalLayout_11.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.groupBox_5)
        self.frame_5.setStyleSheet("QPushButton {\n"
"    background-color: rgb(28, 55, 95);\n"
"    color: white;\n"
"    border: 2px solid rgb(40, 90, 150);\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"    font: 13pt \"calibri\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(50, 110, 190);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(20, 45, 80);\n"
"    border: 2px solid rgb(100, 170, 255);\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.PB_RF = QtWidgets.QPushButton(self.frame_5)
        self.PB_RF.setMinimumSize(QtCore.QSize(0, 30))
        self.PB_RF.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("calibri")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.PB_RF.setFont(font)
        self.PB_RF.setObjectName("PB_RF")
        self.horizontalLayout_11.addWidget(self.PB_RF)
        self.PB_RF_2 = QtWidgets.QPushButton(self.frame_5)
        self.PB_RF_2.setMinimumSize(QtCore.QSize(0, 30))
        self.PB_RF_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("calibri")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.PB_RF_2.setFont(font)
        self.PB_RF_2.setObjectName("PB_RF_2")
        self.horizontalLayout_11.addWidget(self.PB_RF_2)
        self.verticalLayout_11.addWidget(self.frame_5)
        self.verticalLayout_10.addWidget(self.groupBox_5)
        self.frame_11 = QtWidgets.QFrame(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.frame_11.setFont(font)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.verticalLayout_10.addWidget(self.frame_11)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.VL_RadarAnalyzer = QtWidgets.QVBoxLayout()
        self.VL_RadarAnalyzer.setObjectName("VL_RadarAnalyzer")
        self.verticalLayout_5.addLayout(self.VL_RadarAnalyzer)
        self.horizontalLayout.addWidget(self.frame_6)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        self.label_5.setMaximumSize(QtCore.QSize(40, 40))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/icons/Resource/icons/Defend Dynamics.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_12.setContentsMargins(1, -1, -1, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_6 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_12.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_12.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_12.addWidget(self.label_8)
        self.horizontalLayout_3.addWidget(self.frame_9)
        self.verticalLayout_2.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_3)

        self.retranslateUi(FieldSignalGenerator)
        QtCore.QMetaObject.connectSlotsByName(FieldSignalGenerator)

    def retranslateUi(self, FieldSignalGenerator):
        _translate = QtCore.QCoreApplication.translate
        FieldSignalGenerator.setWindowTitle(_translate("FieldSignalGenerator", "Field Signal Generator"))
        self.label_4.setText(_translate("FieldSignalGenerator", "Field Signal Generator"))
        self.groupBox_4.setTitle(_translate("FieldSignalGenerator", "Serial"))
        self.label_14.setText(_translate("FieldSignalGenerator", "Port"))
        self.label_16.setText(_translate("FieldSignalGenerator", "Baudrate"))
        self.PB_PL_Conn.setText(_translate("FieldSignalGenerator", "Connect"))
        self.groupBox_5.setTitle(_translate("FieldSignalGenerator", "Inputs"))
        self.PB_Set_Ledge_delay.setText(_translate("FieldSignalGenerator", " Set Ledge delay  "))
        self.label_2.setText(_translate("FieldSignalGenerator", "PW"))
        self.SB_Attenuation.setSuffix(_translate("FieldSignalGenerator", " dBm"))
        self.label_tedge.setText(_translate("FieldSignalGenerator", "Tedge delay"))
        self.label_ledge.setText(_translate("FieldSignalGenerator", "Ledge delay"))
        self.SB_PRI.setSuffix(_translate("FieldSignalGenerator", " µs"))
        self.PB_Set_Tedge_delay.setText(_translate("FieldSignalGenerator", "Set Tedge delay"))
        self.SB_Frequency.setSuffix(_translate("FieldSignalGenerator", " MHz"))
        self.PB_Set_Attenuation.setText(_translate("FieldSignalGenerator", "  Set Attenuation   "))
        self.PB_Set_pri.setText(_translate("FieldSignalGenerator", "Set PRI"))
        self.PB_Set_Frequency.setText(_translate("FieldSignalGenerator", "Set Freq"))
        self.PB_Set_pw.setText(_translate("FieldSignalGenerator", "Set PW"))
        self.label_12.setText(_translate("FieldSignalGenerator", "Attenuation"))
        self.label.setText(_translate("FieldSignalGenerator", "Frequency"))
        self.label_3.setText(_translate("FieldSignalGenerator", "PRI"))
        self.PB_Send_All.setText(_translate("FieldSignalGenerator", "Send All"))
        self.PB_RF.setText(_translate("FieldSignalGenerator", "RF ON"))
        self.PB_RF_2.setText(_translate("FieldSignalGenerator", "MOD ON"))
        self.label_6.setText(_translate("FieldSignalGenerator", "Software developed by"))
        self.label_7.setText(_translate("FieldSignalGenerator", "DEFEND DYNAMIX(OPC)PVT.LTD"))
        self.label_8.setText(_translate("FieldSignalGenerator", "Hyderabad,Telangana"))
from PayloadPanel.Common.CustomDoubleSpinBox import CustomDoubleSpinBox
import PayloadPanel.Resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FieldSignalGenerator = QtWidgets.QWidget()
    ui = Ui_FieldSignalGenerator()
    ui.setupUi(FieldSignalGenerator)
    FieldSignalGenerator.show()
    sys.exit(app.exec_())
